# Generated by Django 6.1 on 2026-09-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerNote',
        ),
    ]
