# Generated by Django 6.1 on 2026-09-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ECOCASH', 'Ecocash'), ('SWIPE', 'Swipe/Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT', 'Credit'), ('MIXED', 'Mixed Payment'), ('PAID', 'Paid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ECOCASH', 'Ecocash'), ('SWIPE', 'Swipe/Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT', 'Credit'), ('MIXED', 'Mixed Payment'), ('PAID', 'Paid')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
